name: Localization Update with Firebase Authentication

on:
  push:
    paths:
      - "localization.csv"  # Trigger only when the CSV file is updated

jobs:
  process-localization:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Firebase Service Account Key
      - name: Set up Firebase Service Account Key
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT_KEY" > firebase-service-account.json
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}

      # Authenticate with Firebase
      - name: Authenticate with Firebase
        run: gcloud auth activate-service-account --key-file=firebase-service-account.json

      # Generate Firebase Auth Token
      - name: Generate Firebase Auth Token
        run: |
          TOKEN=$(gcloud auth print-access-token)
          echo "FIREBASE_AUTH_TOKEN=$TOKEN" >> $GITHUB_ENV

      # Convert CSV to JSON
      - name: Convert CSV to JSON
        run: |
          pip install pandas
          python convert_csv_to_json.py

      # Deploy to Firebase
      - name: Deploy to Firebase
        env:
          FIREBASE_AUTH_TOKEN: ${{ secrets.FIREBASE_AUTH_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $FIREBASE_AUTH_TOKEN" \
            -H "Content-Type: application/json" \
            -d @localization.json \
            https://firebaseremoteconfig.googleapis.com/v1/projects/localization-automatic-sample/remoteConfig
