name: Localization Update

on:
  push:
    paths:
      - "localization.xlsx" # Trigger only when the Excel file is updated

jobs:
  process-localization:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Convert Excel to JSON
      - name: Convert Excel to JSON
        run: |
          pip install pandas openpyxl
          python convert_excel_to_json.py

      # Deploy to Firebase Remote Config
      - name: Deploy to Firebase
        env:
          FIREBASE_AUTH_TOKEN: ${{ secrets.FIREBASE_AUTH_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $FIREBASE_AUTH_TOKEN" \
            -H "Content-Type: application/json" \
            -d @localization.json \
            https://firebaseremoteconfig.googleapis.com/v1/projects/{project-id}/remoteConfig
