name: Localization Update

on:
  push:
    paths:
      - "localization.csv"  # Trigger only when the CSV file is updated

jobs:
  process-localization:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Convert CSV to JSON
      - name: Convert CSV to JSON
        run: |
          pip install pandas
          python convert_csv_to_json.py

      # Generate Firebase Auth Token
      - name: Generate Firebase Auth Token
        run: |
          echo "${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}" > service-account-key.json
          TOKEN=$(gcloud auth activate-service-account --key-file=service-account-key.json && gcloud auth print-access-token)
          echo "FIREBASE_AUTH_TOKEN=$TOKEN" >> $GITHUB_ENV

      # Deploy to Firebase
      - name: Deploy to Firebase
        env:
          FIREBASE_AUTH_TOKEN: ${{ secrets.FIREBASE_AUTH_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $FIREBASE_AUTH_TOKEN" \
            -H "Content-Type: application/json" \
            -d @localization.json \
            https://firebaseremoteconfig.googleapis.com/v1/projects/localization-automatic-sample/remoteConfig
